---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # base64-encoded "test_app"
  DBName: dGVzdF9hcHAK
stringData:
  conjur-map: |-
    username: LabVault/Labs/LabSafe1/MySQL/username
    password: LabVault/Labs/LabSafe1/MySQL/password
